kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-sit
  namespace: toptal-sit
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
