---
apiVersion: v1
kind: Service
metadata:
  name: toptal-web
  namespace: toptal-sit
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: toptal-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
