---
apiVersion: v1
kind: Service
metadata:
  name: toptal-api
  namespace: toptal-sit
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: ClusterIP
  selector:
    app: toptal-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
