---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  namespace: toptal-prod
  labels:
    app: postgres
data:
  POSTGRES_DB: cG9zdGdyZXNkYg==
  POSTGRES_PASSWORD: dGVzdDEyMw==
  POSTGRES_USER: YWRtaW4=  
type: Opaque 
