---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: toptal-api
 namespace: toptal-prod
 labels:
    app: toptal-api 
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: toptal-api
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50