---
apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: toptal-prod
  labels:
    app: postgres
data:
  POSTGRES_DB: cG9zdGdyZXNkYg==
  POSTGRES_PASSWORD: dGVzdDEyMw==
  POSTGRES_USER: YWRtaW4= 
  AWS_ACCESS_KEY_ID: YWRtaW4= 
  AWS_SECRET_ACCESS_KEY: YWRtaW4=
  DB_BACKUP_PASSWORD: dGVzdDEyMw==
type: Opaque 
