apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
  namespace: toptal-logging
spec:
  serviceName: es-logging
  replicas: 1
  selector:
    matchLabels:
      app: es-logging
  template:
    metadata:
      labels:
        app: es-logging
    spec:
      containers:
      - name: es-logging
        image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
        resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 512m
              memory: 512Mi
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.zen.ping.unicast.hosts
            value: "elasticsearch.toptal-logging"
          - name: discovery.zen.minimum_master_nodes
            value: "1"
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch-logging
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: fast-ebs
      resources:
        requests:
          storage: 5Gi

