kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: toptal-logging
  labels:
    app: es-logging
spec:
  selector:
    app: es-logging
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node

