apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: toptal-logging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: toptal-logging
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:6.4.3
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch.toptal-logging.svc.cluster.local:9200
        ports:
        - containerPort: 5601

