---
  - name: Create a k8s namespace
    kubernetes.core.k8s:
      name: "{{item[0]['name']}}-{{item[1]}}"
      api_version: v1
      kind: Namespace
      state: present
    with_subelements:
      - "{{projects}}"
      - env
    ignore_errors: true

  - name: Create RBAC for jenkins sa
    kubernetes.core.k8s:
      state: present
      template: "{{ 'jenkins-role.j2' | from_yaml }}"
    with_subelements:
      - "{{projects}}"
      - env
    ignore_errors: true

  - name: Create a jenkins pr job
    community.general.jenkins_job:
      config: "{{ lookup('template', 'templates/jenkins-job.j2') }}"
      name: "{{item[1]}}-pr"
      token: "{{jenkins_token}}"
      url: "{{jenkins_url}}"
      user: "{{jenkins_user}}"
    vars:
      pipeline_path: "{{jenkinsfile_path}}/{{item[1]}}/{{item[1]}}-pr.Jenkinsfile"
    with_subelements:
      - "{{projects}}"
      - service_names

  - name: Create a jenkins build job
    community.general.jenkins_job:
      config: "{{ lookup('template', 'templates/jenkins-job.j2') }}"
      name: "{{item[1]}}-build"
      token: "{{jenkins_token}}"
      url: "{{jenkins_url}}"
      user: "{{jenkins_user}}"
    vars:
      pipeline_path: "{{jenkinsfile_path}}/{{item[1]}}/{{item[1]}}-build.Jenkinsfile"
    with_subelements:
      - "{{projects}}"
      - service_names

  - name: Create a deployment pipeline
    community.general.jenkins_job:
      config: "{{ lookup('template', 'templates/jenkins-job.j2') }}"
      name: "{{item.name}}-deployment"
      token: "{{jenkins_token}}"
      url: "{{jenkins_url}}"
      user: "{{jenkins_user}}"
    vars:
      pipeline_path: "{{jenkinsfile_path}}/{{item.name}}-deployment.Jenkinsfile"
    loop:
      "{{projects}}"

